# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:ww55VovPwo/hZxFYdcac2QS2nLFrzT4qmcvQDsZRGBVrtfxCXNua5mkCecoSMFW1HcVS05Wb4o6w9Ce9dr2aJwauei7B59M4U8xrK/ljIt4u310UiQMMbJTXoeeAv+OU8MmbXBfxar9ouG0Njzt+M1twIIHAJLhF6syhbk+sa5nYsjXb/R2j2DkiHjoMrgCCCJF30VZlUG/l6QUMoCMtMd31yPKCPrEBTo7kg8/ePQ==,iv:Hoaa6nIAKij5TCFnmO4AJoaHT0FDNcWFYS6g0vAMFcs=,tag:yLjDmxmGJaTsJIXk1aSibQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1me0lt784slwt8kh7dhrur5jmdss80y8z7k6gnu3kukkqzzake35scqmg3c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByREMrd2hqZWd3aFVrdDhx
        bzlQc2VDOUFuekxUd0U3Mm9rQ3ZRUkZNREVRCnFyaTBtajZTREgvcm40UExvQmRQ
        QnpVRndBSkRkcjhFMmZHK2V0b2ZUTEkKLS0tIEhadTIrc1B6em9YVkxjNW9wR2Y5
        YkprTHUwR0k0Sm4yMXl3UzFZTGhjNEEK+qxE31btWZUTIZJye6twae/pl4RykOsu
        9zEx1P++Wzbt23FRpQKf2fsasOtahb/UJJXLSJCqEEOyS4dFEEuNUQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T02:28:47Z"
  mac: ENC[AES256_GCM,data:jiDP5N7ICCqDZ3CzHknB0UBuCSH5cqOerRIx13r2fXX1RpEEfF50p9JDlsIP/ZGi0qe173500g5d0H7mRhOyOsarn6jrraCIv25FW4M4S9ID4t3g3uLKZU+RNcXJxKjc60Ej45xwmm+nsYG5XIZqfAmO3Fkt4XSH7AQPde2Ec/g=,iv:duyVy5yEsYI4uOpnHmHnhRSmBnZ1Zja+PgGNVqKt4kI=,tag:Nfhisf1VJrpndGm9KB5Jvg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
