# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:FXM3JMePrgsrOSY+NUx4W/pNDVMA+GpTIsGpHkubAwNFIw/El+eXFa3KraGYfGA5FcUdN4yU3GT9vol4lbPZZtyZX2MD6lqyz5f/jnLV6Hd0vhC4OlG/ELTF5GgwZaAu+X4ieLw4jZ7G0lSrCPpUFoTq8GRMSRDQtfq1X3V8sclYCihGnBq5+MX4147w6B4u3+qAgyNxdKnEJsa+Enuns+h3VR/1NaX8tcfCEwZ2Lg==,iv:6gV4d2VvJnW2hlzjGX0x3skNCyOayGmXJJnHjqqA1WM=,tag:PP2xZY1aG0s5FINn4jtGBw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1me0lt784slwt8kh7dhrur5jmdss80y8z7k6gnu3kukkqzzake35scqmg3c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhNVE2ZjIwaGNMOHRUSCtv
        ZjdkM3dIKzhLOS9tcFdWNWZTcXNvQ0R2RVNrCmV0S2NkSEYzaWxnYm12dkF5MFZ6
        RGplVEFiVjNLd244OG9lWUtMZjBHUE0KLS0tIGhxWGVsZmVZU2pMdHhKNUtHRnp2
        cEw3N0sxNThzN1BVMGF3ODByd0dzb0UKL5rP50rkDAhW9l48wKNKrbdsf6oMG0Jn
        aCpix3M3cZT4Ws/k9CcLzY7p/UChwBcwpBMJC7ElJjRHZWpDMIBqKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T03:03:17Z"
  mac: ENC[AES256_GCM,data:kEBwPRkdQWI5m19103psTWOykwNP3NISwtAkq/n83HFPHNpKueX+ldJWawYf7e2SGRSN5rJXKz8bIe55A84nnaLXT07dyPX02QZjZPg3qb1zraeIp7ayXlRk3oYq8E7lO7aWzZ/l7kJEtHf1SVvlaJ30zLPvJeyqmncPzkczRuw=,iv:tr6c3jeDQbF7LtlOLA35YgU8Xfixh4zBpXkGe8J74Ws=,tag:5Ls4Wm9LX7YSleyX6SSFpA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
