# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:/tjyPqADhaUA8MPy8vvAbrDTkSfFm3BhqAJFE5M7/KZzpzUBYe0KFza8tbNg0E27oBCex/SZgSzsYkBGAMEp1trqYlh7hBzuC779Mp07ukA7XNrwjlcLMPTdXQiPDs5KLeD47h6fGsgD+S+O1VjQtM4Ql3NqGWkLij5f9ng7jlj+ZbAjwV8AnBYWHE0ucJsknwLbmC0EB50Ns76Hj6SIn5VJi2M7vaQHlxirw0p1xQ==,iv:IXGcxGwV9x1FSYHMqWccT8QOsHQicGTweFIifRvk/Qc=,tag:+r14CCsDpJk2jEapiDiexg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1me0lt784slwt8kh7dhrur5jmdss80y8z7k6gnu3kukkqzzake35scqmg3c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSXJaejJjU2IrOVhpVUZo
        NUNSSzkvcnNZaURFM2dXaXRnd0NmZkVQRUEwCkVra3lXenhuaERGdTQ1bzdiTjli
        RUtzcDFuNjVlc2NpaFdVL1ZaZ1dCdGsKLS0tIDg5Vm9yWXRtRkJyWkZGTFNteTlq
        anV3ZEs0WjRuc004b2luM0Zndjc0SzgKXQCwMAN35wWW743SjOrK/8w9RQvDztkq
        81v3kXVBXQD5sDNhgyUOovtFIMp/89R7fZhAfWgLdavzLo1CnWWmLg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T03:11:50Z"
  mac: ENC[AES256_GCM,data:ruLTKo/mltx0tH0FW4tenzbwzBoLM9qAk5wXXmIHAGhecEWMRuOhUOXUYehrKP3f4FPqVVyzhKdwS6bB+wSA1lF689ORSIzORt8YmnywKKLm0TMughk+5prKfHnVVI44bKpGcCg62G+o0qeBxiSyGer1nWUjnCmCC1R5rnyh3DI=,iv:90VQ0du5V2IlRXIXDcbm8uJdFBjaSw5ggkezkUoBOWI=,tag:shQRh0GznTuVs3TwCQh6aw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
