# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:9jlXLMEtd02zwM5DqCctjFZi9NeyUGHxPexAQM8sD4iamCUCI33wrQ==,iv:saqO5JBDIwUdgQYoFK1vGIC/3Nt9cxbw6UwFQmhH1yo=,tag:tgeLHKEQ6fpqo8lJQbNH6Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1me0lt784slwt8kh7dhrur5jmdss80y8z7k6gnu3kukkqzzake35scqmg3c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDS0ErWFhjdk5CUjhZS2pD
        bzgvZnJmRExEcGdIbFpzSjViME5Vb202cVZFCk1tbHhEUEJxMUJXMkI3YXNZbWV4
        am92dWZ1VXNoNWhMNkcxVThhenUxcUkKLS0tIEd5YUNlUElRN084SHk2T1U1SnZm
        OU5hN3owN3E5V0ZVZFFJUXloY2MrVzAKFrlOE8LeS0elLh1qTtwPGhTqz5DBCcF/
        M26hNO1OOa5ltWDtOg6JQkENaGTjG3O3Zo7uxEbEeku0w6LlsNvfog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T02:28:47Z"
  mac: ENC[AES256_GCM,data:hFZaJPLE6wD+1ZBJN4uopHVRlI/7KqWi2yIxSpykoK3o5rlgXr8mohvPLsKiGUcy7SxIhIO5Rzgy3bnLs4YhQs27rL6JPE0o6fTIdxcI1yVAmZ0fdJCRfbzSk/ernScoC7NJ2FUEDClZoYYOkXs+Oj02eOEIV0zV73Q4nfuZU58=,iv:EhiU9Eqly7Vy1paieZc/YAcXgGVSPsUpGXx9aN5Oq/0=,tag:4JJ1AHt/o6Kb43FYdx1/3w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
