# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:SLKDOp+uNYeErhz7ylUQVgZa8BRZChA8qKOMGfRCh7BSh5s8AsnRRA==,iv:Q9xXwlYL04k5DxhKuc+CJTUtYGpYEx59ZelosZq3cHQ=,tag:jkYUt80WuxRvRsP2TUsdoQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1me0lt784slwt8kh7dhrur5jmdss80y8z7k6gnu3kukkqzzake35scqmg3c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBaDlkemI1TFJYdnRVOThK
        WGpyVGIwNTRHc0VnSDNCcnJqNForcVFreVI4ClQ4NEdicnpCWjU0bVFEdTl1cUw3
        RllIN2RJM2ovZGdxM3liU1E3TFAzY28KLS0tIHUzOFo3RHVScnJwLzUzWkQ0MHFB
        ak9yS3ptVnMrU0tlMUtiMUdabFpZK28KHrFZw6IJQZ5YdKhuBWzVXK88DYZK8PRp
        vsFONXmfZVaL0Il5r+ZxG6OLGGz+RFcUmP3mRZNcF/MYGlw+pFJbOg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T03:11:50Z"
  mac: ENC[AES256_GCM,data:TFS4hJQlKbM9N+BnPAjxPd2fy1qBZdGJihdJnLCLAyCHaBxLxiv/Wjdpat82rVC4QZvMamomm7V/HHYfxkDUwvjmwy3tQx9yi/K94j5nzTRBjZ6wFlhvkUoRBjrKMC/yZl2rFkw2jRh+x9Z9NQBf+Q8sgKM4LsvgDnu77f16wp0=,iv:6LPXsoaOJGSyLhWyUen5/Wwq2EgviCqOVV+Z9kPUvWQ=,tag:yvLOAFJNA4YlZxEpLIi/gg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
