# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:9pu6MzY2UPNZ1UB7x7hiS1u4qGDAJJQzru/vFZwR7G8ZxszJyu0VfQ==,iv:DdKMi/GCbAAEEbAXLHY0hM2b330z5Ru5occEyL1+mtI=,tag:3emkhIfJOe3o7vp1YMgH+w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1me0lt784slwt8kh7dhrur5jmdss80y8z7k6gnu3kukkqzzake35scqmg3c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5N0tMTzFxMS8raVpBNSt0
        WWs0OUJSTmpKWlkrMnREdENHcDZ5ZklNdXpFCmg3bXhpL0JBUS9GeUtHQURkN1d4
        VFJhUHh3czRYS0JOT1pwUHFESytKVW8KLS0tIDNSRzN2T1RGSXMzSnV6MGxxalZr
        cnlnNFFtMnpwcENOWVNzeDI0dTRCYVUKvpYRHMUAzpLoR1o/ibSVGkLxBzdZspLM
        TwfQG/G6c+P6BC3mJ97G6pdM95dF5BzSX0Q1K+jZwQ41gGW5V2sY6Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T03:03:17Z"
  mac: ENC[AES256_GCM,data:4l5kKWn5yj26kYrglwHgTbqVsk5gP6l14jRmb9vaJq9Jz7IfstJlsaEqiQRG7Eb1REGq7GNgKCtEpXrQ8ulZOqmteu23lp4ocFFG6B08VfLfWRe3xZ6NA8wQgN2M/S8e9+mUPDB+JxHQ/6EYYFPecNOPsxn0pH/KhkDvTLbu3cs=,iv:pF5QlmK2ssfhSRkwwtmfO5pyV0zu6Q5pomTzIwYkxs8=,tag:sDJmx2kGCgCfnaGlu8Yhfg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
