# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:AuQ4zb71OWWzFnKqLDZWpHHdjbLXGqs60CCKO6ud3Cs=,iv:zods437+jG++k1Gpu852VP3Fvsg0S4XNqsyD255mS3w=,tag:wM6EBK/8Jf2yCwD71b5ntA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1me0lt784slwt8kh7dhrur5jmdss80y8z7k6gnu3kukkqzzake35scqmg3c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaWFXc3BXN3lqalk2dmdq
        ajB3bmFRL0lqdmgyVXFhZWdEYWdGRVRJQ0RRCjJ3ZzFlbFcrb0FQcmpPZExKRUVh
        NXNvcGFLekNkWlVIYkcyeExrSG5BZ1EKLS0tIEFpS3dUWmhEaWNFYkxrTEN0MWI2
        ajBNMWM1MXp4amZGdnRMR1JQMUFlbEUKRIKUob+etGi1rIDWEij0jLQWyVDwnvz2
        oXkiP+DvlyfOyTP2o923T9eIK6LPGDNfiro8BG1UBoroCJlu9oNx0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T03:11:50Z"
  mac: ENC[AES256_GCM,data:HgLZBsGOKSHUqeinX25epCNbbfAJN/cJP6extzJ76HR9PhoXnzNcvYR1pDnHxZxnBk85wbGy5l73niYXSskHWbPURQCn+j9KcjpFS4UYgMcjyprvWl+M0ENjC2Ua6nONeG6y8Nu6kxDeqxr1Co6QBkmCIej+y+XvfcBYxh+3i5o=,iv:Q1+YKgoQCCrtS7gGfHI5J6hhmU4FrnPLA+Tdak7zNSg=,tag:Ebk/FnSqw6SEL4mnX3XvDg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
