# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:OAhAI552kWP8Do82g9VRCW1REthAsK3vNH6/6b95t5M=,iv:mSqdOGXP6AFrYTRy65u9i4CJDcknOxlMKYaeXxXAnOc=,tag:IzSoXAmcb8mB5D8cCPw9jg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1me0lt784slwt8kh7dhrur5jmdss80y8z7k6gnu3kukkqzzake35scqmg3c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WndNNjdibFUzR2VSSU55
        ZG9vbGMybjdady91WXNOczZpZHNWc2c3QlVNCjdHcmNWTENRcEd4REFHeStXNDFI
        c2pDTStTb0N1UDA4ZHd4ZGd6cFlKeVUKLS0tIEtzd0g1QVFONjh4MEdBMTVSblJ5
        aDdHeVpCek9PSWI0M3N6K1F0c0NvREEKSycWzYwcIAC7SnQGq9SPG1E2ZZ3V9C9w
        KpqOFd+tnq9kzPVJD6/d5rjj740wF5y4fYj/kCPG/p0G39bsM0WvrA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T02:28:47Z"
  mac: ENC[AES256_GCM,data:d3Rb1eVPMjDIg5DFyjQMlneb5wKd2Fr7t9g4XgM67FdolKCV3wAvZqxdI43sspETWsSM6jfpdM/Aj4kMM2XuWINu8PtbXydSBNXeO/DglIUgTPPJfVO5C7mMsWUMoHDKe0RWpKWDhczKyI2Fjl6JieQkb4BdBSJXepsUijfhROo=,iv:0ZORoLEt7onj6ZYvz0thh7jws+NYcNHpDI9zwdACxyc=,tag:yJ/dJD9WWw3VYqNwKkJENw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
