# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:XIUHOUE30ktBT1bjWk1tqxOF2Y4SCU42VB6wAsTdmEI=,iv:hjkSHDmjvtkBZmGYjiDyO2VgSFeOSJJeY2U516VTNxE=,tag:r1uiXlfVj4fGQi5pE1NoSw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1me0lt784slwt8kh7dhrur5jmdss80y8z7k6gnu3kukkqzzake35scqmg3c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvU2RGeDhuaXRYa0FOTkdB
        UGZUWW45bXRzMkVuODZRYzhxZUY2TDRldjFFCmNWSStnWGJyK09Wcm9ZQTFCUngw
        NUp5WXJFUlBqM2RpSWtpUWJYOHJKNkkKLS0tIDZiN3JaR3duSkEveFNUYVJGTEUw
        TnVIWTQyNFl0KzZUd0pKZ0NnczVKeGMKRUJZYMxFUvYn/2C94pZdFF4IARDS++8V
        ogpt1qnliSrteTVcQyzM5pwqA6AEfmIAQ2KjbQVtHM/aBx1ldSrF3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T03:03:17Z"
  mac: ENC[AES256_GCM,data:DjrqP4Jr5PPmnP4DLlYNJUGspOedjjZhcg/B18u8fnwwjsjsyV2Wi83CEGDG1F3HwWKuE5FY66JGZcncU9b/tb2xFsKCXYgfFDciGAG1ly6Au6uh1H9Tfykl/ncLdnE6mxY4IjAmlLFgunHcuUWGAFdlQDggI3YmHnSqEUS0608=,iv:VZy6ZBpNUSyKykccRaeDa44MFETybeVm6tiikkncBi4=,tag:uxNB3lpXVVj4ab0ilMJRhQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
