apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:nkQaOzZuE0TLs0auXAg3,iv:sesXXZalQ2iFFSkjiOPToPwP8HtvGuJVDY8Hd18Uaf4=,tag:0gXBmruASjEaNzZ7V0Bbgw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1me0lt784slwt8kh7dhrur5jmdss80y8z7k6gnu3kukkqzzake35scqmg3c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQVRYUXY3a0dUMlBEclZL
        M0EydnFsdjMrVkVZWlRhOHRzcUxKeGxuT1RBCnRBUzFQVEFobEZSY1pRL3hJZFpD
        NUNyLzI2aDFqV2FBZ3ZZRWVjSlRkaTAKLS0tICszQUx2QVBITVZuTzFMTW9ZTnhx
        RUZoY3VJU0poSUVWdVdIZFRJTjNMVkkKPTl8am5ZAmH7SWOf+9J45V22gzNf/6AZ
        g0MYiuW+agdBVY5R3JmxmpOcUGSjSf12KIJVHgDc60N//9G4goHo1Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T03:03:17Z"
  mac: ENC[AES256_GCM,data:mZiJ/jEkj+DHVD+k8EZOUd+ziAF76zOrlElQ4Ytbks/gw3UjBXSzV31//Dn4179/1/vpiZ2AJ6SQbNhn0PCxnbTGDZs6YtPOSjYp1zkeL3+2Ys90CUBluYOb2mymdxFf11iZn3JB4H0d8seiG1ApevtIrVKEjdtxcsDnNzRbf7U=,iv:RRRFP5So1dmjUj8mlCM4uyF4J24KFCFUG4c00/tHcOk=,tag:1FajKVRYAfHWm0+O9SJ2SQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
