apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:tUFSSLohJg7Ms/KbeBfO,iv:pi8U/PuswS0vXc+7LvaPOj+XReIPviaWrxDHxPup7IY=,tag:5fnyVc7BSkOf5M7Lm3v6ow==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1me0lt784slwt8kh7dhrur5jmdss80y8z7k6gnu3kukkqzzake35scqmg3c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIc2hiOUFxVlRoZjR1YkJp
        NExtS0s1S3NNZUlaTWo4WXRxeElNQ0JsNkhjCkQyZ2xqOXNGTENYSGJGdXB5a2hk
        eDhtcFk4QUIwRHd4YllPa28wOHpDem8KLS0tIHJUbnJjVThpbDNlV243UGVoREpC
        N1NjbklGekVsZFFnaVRyVmxpWEQvU1EKMRX5RJDzTOpisRoF1qbvDQU6QM+jBOie
        2gNs8e8z4p7IL4g/0X9sEBy/8hp4qrNj/Fv37ehlMw854/QF9K21nQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T03:11:50Z"
  mac: ENC[AES256_GCM,data:weGdx+L36xLHgHUqNr/fY+69wOE3FAa7g+DVKWQfFtDWaEbc3f3Y65Sh8cP9PK59FBZrg04CHsJVBfzwmHkdhLLE7OEjyOPBYpkBmjhGDJcHO/4K5dSxhay0dwI4wpTuy6Nm4fdi8Ns57loAN0lnAFo4R3pTmzaNZkVZT7AHJSA=,iv:El4+tocyNQB6IfZVir/knWC/r+Of+8m/YhXuPN5/Zdc=,tag:jZ54IfUywRiLzQfa4K3+NA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
