apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:lrQkIJ31hVUNgu9Mdf1A,iv:kPnBljjtuThetCl2lBVLwu8m3VZPIvaMrLpFyLIFSs8=,tag:YMT/FjhdW32LTm8PsayClg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1me0lt784slwt8kh7dhrur5jmdss80y8z7k6gnu3kukkqzzake35scqmg3c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXczJXYXVjd1NoZDFzSGRj
        U2M2MEdNSDR0cmJNU3lmd095MElWVTRNRVdvCjZsU0FSSFdLeUl1alg4SU5FblZu
        K0c5SkdFSGs1RFlmN0xUY2pMeCs3TlkKLS0tIFpVa2Y0Tzl2d3laazZqb2kySmhh
        Tk9HRkFDaFV4WEtuSDlabVJkMkZjQ28KOrUpd0kOwWKiPwCxyxIywOC21xJ9cbZn
        4kQrKcjsoOwR8OiC4+gMXxo44Mlck0SMOO/aRLU8wpboxjSd1VvD5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T02:28:47Z"
  mac: ENC[AES256_GCM,data:BkQ2wHBwER/qZvkGZzLeiLhh75fOB3tAUtp6Iz3203uQC3xG11rvhKpJE7oMykrCNh0lyEvaF070DflPs3pG2LXCA8Q1GdElh1YWp3/A/tqCDiiQ7DsA0kZTRfJuhm05M/SXkHW6arkMHGKmlRI/aHVK5TyW8Q8DcV0WBKq+YXU=,iv:o14nJZQa9SuL+PAqcFsB1VVXI158UxlrwQ5mc2Z+I6A=,tag:vrg1lFUypRzkaaKkPzTP7A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
