apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:iTrNNU4ZDnSxWqu6Glgv9Ib4DLq9A+FeMwyDAc5ZIaCOoSU0kDe5AIx9JiGN7z2lLWYvvcyk7ypa6TlvLSKEfllaI0aMQa48cDM=,iv:U+ngkbpTIaNR0UeyFxYgMykTzn3R5eRArWfPK/rBYmY=,tag:2kbWoYkRm/TXii7wzpX6QA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1me0lt784slwt8kh7dhrur5jmdss80y8z7k6gnu3kukkqzzake35scqmg3c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaEZIWkE2VXRtVGgxZW4z
        Yklua0RBbDBaZllEUzc0QmpjUDFkMU9wYVYwCjh5a1FzUHZrOGVZR1ltV2dCVkRT
        UWovanJkMkpST1d0M2hLcXpycnVhcFEKLS0tIGZoVFFVSGg0VmVZUXV3YzdFSlRG
        VW1qUEc1U0NoU2h1WTlxWExLVS9WUVEKGNAoD5fcARhP/oEXCcVZb3Xy2hdJDw+9
        pUz4YQ69QgGMB7cpR02YFNsN1bOK14Kb24CBvnUIwXbAcF8peMxHcQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T03:11:50Z"
  mac: ENC[AES256_GCM,data:E1j8XqexVaYtbRrQqjgcdwswCC1g3A0+AtrQ/0h6FFJNzXnGnkm8cHefZBO0/T/neoIzbFBVQ1rhw3pnltnP0YKymQvbyid+7kiOvgZcVsakCWMkBAufqTo5omjf0TmoO6JIFOeu/wg2CT9CrpHf7JljSwp4yEkPduEedFCDdfo=,iv:hnPxIVmBdJ2mTZKehVsxA5wK8OUZdUaHmjZQP4zkDVU=,tag:YJZK5+itlpMRm/mTNgAMmg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
