# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:4TVQgz5wUOU0veV+5uxTdP8vWcmNgPShcjb72UxjTEvCSuKW3CPIpg==,iv:f9Xvyg5Cab/TARMf1tLxMHycY+++XvWwAw1H7XMYZas=,tag:X0GQXqejJEIuA7cddfEp5A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1me0lt784slwt8kh7dhrur5jmdss80y8z7k6gnu3kukkqzzake35scqmg3c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VnFnSnk3dnZYRm84SmQ0
        VzIvc1JlNXZ5STgyQXpVbDh6b095cHRDd0Q0CjlRVFFKSHZzWXFxSmNzQXBlK0Js
        VXVqbTUrTjA3TnNRWElvbjhyU0ZVbE0KLS0tIGI1VS90OVlTNlRDYzFqQ3BSeTZP
        YlNpNzNYeTNrcjdlLzFsVnZDZEJtMlUKRI9ENzwdZ7e3Pf1SzR3U2yyHyrgZb2YN
        67nPYrX0ZYogA44g1hgrYiDL53pdkxv5bZ/yqPhyXX7BOGZoJVLF+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T03:03:17Z"
  mac: ENC[AES256_GCM,data:4JZqqPAAaB803xF8mAC9cDGtzS7KTvdXHRVJLE8kSPt15Svf6w0PdubXO1pZgeLbtT7pTTcbgHlyIryYOnTiqd31Slh4C09pCz9dFH7BOlbxYYonYVgCp09lTYE6ltXT0+9PoIW6kd9ajew8t/8Uh1tPL8VHSyalVr4Vhw2WjyA=,iv:ufWYq+swKpAn3nzOuH6nDNkUAes6TKL/xpORKk3GZvg=,tag:EscahhTvEFFyL8QHtaMyDA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
