# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:BApC0LT8B36PQCJR22paRgZcA4s17XC3X8daAjjLgArvtZ9//eZOmw==,iv:y/G87YkFBtFaGO6RZED53qarcZLF6ZVjr2ry3ixVR3k=,tag:2vsN0osWO5TZ5I+Ma3/+QA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1me0lt784slwt8kh7dhrur5jmdss80y8z7k6gnu3kukkqzzake35scqmg3c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCc0FFcWZBdlZQZG9XWXdZ
        UWw3RGNtZ3VkWUFobm4xN1VTMkJvL3A3WEJFCk1xcGtPMU4zTnMvMGxTZkltVkNT
        ZTBsdHdWSlQxbDJiUGZIR0k1bGhFbFUKLS0tIEJxVVFxR056T0VhK2duVEx5SjhY
        WExwV3kxYTZGeUlzT3FhSi9sMHQwTUEKpMWR08QeATnlYGFEepAkyMYwwltK1X+1
        EGUTEnSBdiLIvuiE5YvEo+RpsZqhZDAvu+nL/lXIyvs2/CMldn01pw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T02:28:47Z"
  mac: ENC[AES256_GCM,data:EOSHQHtVxQXSOMx7Wvx6tpXGk5m2Rle1gJ+yy4Bxiq6kwN8Smsmc4vBB55wp0xKc8PWBUbmQg/KnYJ7pySzWk8BCoL4rSWaNfbyGwxQpbLh3vvz74WxZJxV0B3qEpziPn2PsE/t5yHBnioPmjhVzztfNC++Doj7ZAr1Xvf4evOA=,iv:v8EhBgLkbJ91Nt/y58+ztQ0Cgf/sUErGReLxDASKYG4=,tag:6asZz69+E3ikL4og8FLKCw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
