# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:sxz9aECxrDw1p0l2w5dEqnPxWWqEE++JCeGzvo+0Jf2PoUP5tcZ7tQ==,iv:+vANI/CpD+awkXuM1K9X4TOFRzxIibDOsRRQo9G7aXw=,tag:V/7LGiEoTPjOxCgPRoAXvQ==,type:str]
sops:
  age:
    - recipient: age1fzfykckjr9lu8t5d0v3q9k87er0kscjfh70r2y7v3akq0n4smudqlmmnly
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueUM5MHlNdUNsVjJHSGF0
        NWtveWFnaWpndVh1amNMTS9wZW1RK0REcWpnCnVOMkF1aXZqMkd5Wk5SM0lvUVhu
        WHlqY1JBeG4zR051N2taUmYxanQvYm8KLS0tIFZlSXVtZEl3cVJkdGRUcUI5V2RT
        ZEcvR1F2Q0NLMkNIUDRDS3JZNktzZmsKxEDDYsfSlm6J44NwASfQPZTf3IkzSBq2
        igT0buWGANsJhueWMXNLNBInRZKS3Se6UdfJCLDj6/DHd/J7BvD6vg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-06T21:56:47Z"
  mac: ENC[AES256_GCM,data:4J0rztLpiErvhJOTWV/EJkJid1h7en+fT6MuLlLUKmBfv+vIVS8Dr7qBi3cTZSzqYTY8aeeLE5rpo2fWy2Ya4kx0XHudHwMvjLgAR0oWBZhEk9Cc3IYX/cgfwXwBg0UaPB2OfuzYx6YE0w51TZ/BOGMU44LV5KIZ5N+PxPJ1KdU=,iv:6sDfXop7m942N9zUbT+4lJwAXHt2bwamnJO3/8FF2VA=,tag:0Tf0wEiBk9nnnvxMm6Ir9g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
