# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:PWapSbkKU2L4Y0V1LXfUFnorJTQMu91eZibtuCamZvLwJPU3eEDc9g==,iv:S+vI81rvnKCIYS08cThAfcwX/iPL2EAtAi1U2NqbFH8=,tag:cbeAlSP/Qbhy2cKlQoTDCw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1me0lt784slwt8kh7dhrur5jmdss80y8z7k6gnu3kukkqzzake35scqmg3c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3alBPeW5lNjRhdXpSQnRQ
        VlROcE01dXIrbmZZcG8rR1BXbHFBeWZMcVNrClRsZVFrT0lTeGpSbjlBOGk2b1hY
        UGJOdDFXYllTcVdNc004eWk3ZnUzQWcKLS0tIFVtcXpUL1ptM1liUjJhM200M041
        WUloeVIvUjljVWxJRUhmMEo3RDhiTE0Kl6TcmJZivMVt1kdndfQj/rLPhDANXlMI
        SgcyG03fjeB1hM7mkK/RlexJ+unYrF+gTCmB0iEE2+WCrIvAdcFdFA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T03:11:50Z"
  mac: ENC[AES256_GCM,data:Ry/yKy4YEsBvTP813oCEGxR2hE8z+Gj6WPtrC+MgFIwZzbmihtYwOEAA98TSL/4AiIeIrmj6nEdLiqY845Tna5hy2EaMpEsWBJTySGEIteIEQtigA7bAYQuMhS0mzFGUdWHKUg2+DQOY8RclFWXmT9fCoLb8rThlwJ77ut9jJ7w=,iv:VN7gOE0SNNDhYYvvy0aBmBCnDXfjvkBvcNQ2EkRxi/E=,tag:TMXKHnbeRsaLJtK/ImnMxw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
