apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:PdOnG/JBYnGGskYedaIl,iv:j6UtZN399QhtxDznZoJgF6bTK5XbkEITsLfOaB0YgUs=,tag:lCPSgEp3+iW+fKPA9kEBvQ==,type:str]
sops:
  age:
    - recipient: age1fzfykckjr9lu8t5d0v3q9k87er0kscjfh70r2y7v3akq0n4smudqlmmnly
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUlZPK1ZtTCtjSVJZekpr
        MUkzOFhBSnU3MVJjNnl0SDJRRi9RSnZJUVZVCkxLZVVLK09iYkpTNWJOMWI1bnVS
        blVDQks3TGpGakVaa0pMSTRuSTlhR2sKLS0tIDFYMElYYzg1cVM2ZytNcE5oV3hk
        b0dJVVpWNHBOMXdFOVZicnlVN0xPR1EKmxlr9UEsR9LUJhLsi0rV7ICdiR/bZxu7
        tDQdNV4lZYhRpfuJbKoskGdSo3Lvwp0osTAx4ULgzdV1rKIKHtCLzA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-06T21:42:37Z"
  mac: ENC[AES256_GCM,data:uaXJtIGkFRoyabSoJdHvpy8rnktsjqo4yoQU6UW7TyU7RnH23BxoqxuBf9Op2JwbRfYUlEr6+juEBfQSpor3apd4tQM+4lGF5PRAsXcqupXhT97wXzDFlWqPVDV50xtg6pozquzQnRP+2/pSOKYmAqVSEXve/3ab6grDsiU5J/o=,iv:rykE0RW2jREMs6wB+B0FcfH80kS7uSKioSGN9lSkq9g=,tag:P0wTSMSuYmJ9PztfyyZh7g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
